In [33]:
import csv # importing libraries
import pandas as pd
import numpy as np
import os

In [34]:
file_dir = './vosaic_model_verification/S2_T20_Dinesh/' # declaring the file locations and data
sketch_csv = './vosaic_files/T20-S2/P2.csv'
video_buffer = '00:06:20'
vosaic_video_duration = '01:35:24'
video_name = 'S2_T20_Dinesh'
csv_name = video_name+"_vosaic_sketch.csv"

In [35]:
df = pd.read_csv(sketch_csv)
df

,Start Time,End Time,Duration in Seconds,Form Title,Moment Name,User,Moment Sequence,Number of Tags,Global Moment Sequence,Comments,Tags
0,00:06:20,00:06:25,4.727346,Onscreen Reps P2,Sketch 2D,Vishnu S,1,0,30,NaN,NaN
1,00:06:32,00:06:36,3.921587,Onscreen Reps P2,Sketch 2D,Vishnu S,2,0,37,NaN,NaN
2,00:06:47,00:06:53,5.781360,Onscreen Reps P2,Sketch 2D,Vishnu S,3,0,52,NaN,NaN
3,00:10:09,00:10:39,30.203446,Onscreen Reps P2,Sketch 2D,Vishnu S,4,0,124,NaN,NaN
4,00:10:53,00:10:57,3.527709,Onscreen Reps P2,Sketch 2D,Vishnu S,5,0,139,NaN,NaN
5,00:41:19,00:45:42,263.545932,Rep P2,Live Creation Sketching,Vishnu S,1,0,484,NaN,NaN
6,00:41:22,01:07:55,1593.161833,Onscreen Reps P2,Sketch 2D,Vishnu S,6,0,485,NaN,NaN
7,00:46:38,00:47:45,67.365396,Rep P2,Live Creation Sketching,Vishnu S,2,0,533,NaN,NaN
8,00:48:08,00:53:23,314.993148,Rep P2,Live Creation Sketching,Vishnu S,3,0,534,NaN,NaN
9,00:54:01,00:55:56,115.731561,Rep P2,Live Creation Sketching,Vishnu S,4,0,536,NaN,NaN
10,00:56:57,01:01:45,287.592736,Rep P2,Live Creation Sketching,Vishnu S,5,0,542,NaN,NaN
11,01:02:19,01:03:22,63.331972,Rep P2,Live Creation Sketching,Vishnu S,6,0,581,NaN,NaN
12,01:05:36,01:10:18,281.312236,Rep P2,Live Creation Sketching,Vishnu S,7,0,603,NaN,NaN
13,01:07:57,01:08:24,27.053106,Onscreen Reps P2,Sketch 2D,Vishnu S,7,0,636,NaN,NaN
14,01:08:30,01:08:34,3.442131,Onscreen Reps P2,Sketch 2D,Vishnu S,8,0,644,NaN,NaN
15,01:08:37,01:09:03,25.385123,Onscreen Reps P2,Sketch 2D,Vishnu S,9,0,654,NaN,NaN
16,01:09:23,01:09:42,19.263174,Onscreen Reps P2,Sketch 2D,Vishnu S,10,0,666,NaN,NaN
17,01:09:46,01:11:36,109.449476,Onscreen Reps P2,Sketch 2D,Vishnu S,11,0,672,NaN,NaN
18,01:10:56,01:12:41,104.216912,Rep P2,Live Creation Sketching,Vishnu S,8,0,692,NaN,NaN
19,01:11:38,01:12:44,65.863853,Onscreen Reps P2,Sketch 2D,Vishnu S,12,0,716,NaN,NaN
20,01:12:50,01:12:52,2.493197,Onscreen Reps P2,Sketch 2D,Vishnu S,13,0,744,NaN,NaN
21,01:13:24,01:13:30,6.292607,Onscreen Reps P2,Sketch 2D,Vishnu S,14,0,756,NaN,NaN
22,01:13:41,01:13:59,17.436009,Onscreen Reps P2,Sketch 2D,Vishnu S,15,0,760,NaN,NaN
23,01:14:32,01:14:38,6.016868,Onscreen Reps P2,Sketch 2D,Vishnu S,16,0,779,NaN,NaN
24,01:15:14,01:19:13,238.473550,Onscreen Reps P2,Sketch 2D,Vishnu S,17,0,792,NaN,NaN
25,01:19:33,01:20:26,52.958273,Onscreen Reps P2,Sketch 2D,Vishnu S,18,0,879,NaN,NaN
26,01:21:19,01:24:14,175.254643,Onscreen Reps P2,Sketch 2D,Vishnu S,19,0,903,NaN,NaN
27,01:24:35,01:28:06,211.792014,Onscreen Reps P2,Sketch 2D,Vishnu S,20,0,939,NaN,NaN
28,01:28:14,01:29:03,49.401451,Onscreen Reps P2,Sketch 2D,Vishnu S,21,0,1000,NaN,NaN
29,01:34:58,01:35:10,12.062358,Onscreen Reps P2,Sketch 2D,Vishnu S,22,0,1065,NaN,NaN
30,01:35:13,01:35:24,11.400551,Onscreen Reps P2,Sketch 2D,Vishnu S,23,0,1069,NaN,NaN

In [36]:
df.drop(['Duration in Seconds', 'Form Title','User','Moment Sequence','Number of Tags','Global Moment Sequence','Comments','Tags'], axis=1) # dropping unnecessary colomns

   Start Time  End Time              Moment Name
0    00:06:20  00:06:25                Sketch 2D
1    00:06:32  00:06:36                Sketch 2D
2    00:06:47  00:06:53                Sketch 2D
3    00:10:09  00:10:39                Sketch 2D
4    00:10:53  00:10:57                Sketch 2D
5    00:41:19  00:45:42  Live Creation Sketching
6    00:41:22  01:07:55                Sketch 2D
7    00:46:38  00:47:45  Live Creation Sketching
8    00:48:08  00:53:23  Live Creation Sketching
9    00:54:01  00:55:56  Live Creation Sketching
10   00:56:57  01:01:45  Live Creation Sketching
11   01:02:19  01:03:22  Live Creation Sketching
12   01:05:36  01:10:18  Live Creation Sketching
13   01:07:57  01:08:24                Sketch 2D
14   01:08:30  01:08:34                Sketch 2D
15   01:08:37  01:09:03                Sketch 2D
16   01:09:23  01:09:42                Sketch 2D
17   01:09:46  01:11:36                Sketch 2D
18   01:10:56  01:12:41  Live Creation Sketching
19   01:11:38  01:12:44                Sketch 2D
20   01:12:50  01:12:52                Sketch 2D
21   01:13:24  01:13:30                Sketch 2D
22   01:13:41  01:13:59                Sketch 2D
23   01:14:32  01:14:38                Sketch 2D
24   01:15:14  01:19:13                Sketch 2D
25   01:19:33  01:20:26                Sketch 2D
26   01:21:19  01:24:14                Sketch 2D
27   01:24:35  01:28:06                Sketch 2D
28   01:28:14  01:29:03                Sketch 2D
29   01:34:58  01:35:10                Sketch 2D
30   01:35:13  01:35:24                Sketch 2D

In [37]:
# function to convert string time (hh:mm:ss) to seconds
def string_to_sec(start_time):
   hours = start_time[0:2]
   minutes = start_time[3:5]
   seconds = start_time[6:8]
   
   if(hours[0]=='0'):
      hours = hours[1]

   if(minutes[0]=='0'):
      minutes = minutes[1]

   if(seconds[0]=='0'):
      seconds =seconds[1]
 
   hours = int(hours)
   minutes =int(minutes)
   seconds =int(seconds)

   sec = (hours*3600 + minutes*60 + seconds)

   return sec

In [38]:
# function to convert milliseconds to hh:mm:ss format
def mil_convert(milliseconds):
  seconds, milliseconds = divmod(milliseconds, 1000)
  minutes, seconds = divmod(seconds, 60)
  hours ,minutes =divmod(minutes,60)
  
  hours_str   =  str(round(hours))
  minutes_str = str(round(minutes))
  seconds_str = str(round(seconds))

  if(round(hours)<10):
    hours_str = "0" + hours_str
  
  if(round(minutes)<10):
    minutes_str = "0" + minutes_str

  if(round(seconds)<10):
    seconds_str = "0" + seconds_str  

  time = hours_str +":"+ minutes_str +":"+seconds_str
  return time

In [39]:
arr = df.to_numpy()
buffer = string_to_sec(video_buffer)
buffer # adding buffer time of vosaic video start , so that timings match

380

In [40]:
video_limit = string_to_sec(vosaic_video_duration) # the duration of the vosaic video
video_limit

5724

In [41]:
rows = df.shape[0] 
rows
cols= 2
intervals = [[0 for i in range(cols)] for j in range(rows)]

In [42]:
fields = ['timestamp_A','timestamp_B','action_code']
vosaic_sketch_tags = os.path.join(file_dir,csv_name)
with open(vosaic_sketch_tags, 'w') as csvfile: 
    
    csvwriter = csv.writer(csvfile)# creating a csv writer object 
    
    csvwriter.writerow(fields)

In [43]:
for i in range(buffer):
    timestamp_A = mil_convert((i*1000))
    timestamp_B = mil_convert((i+1)*1000)
    action_code = 0
    data = { 
             'timestamp_A' : [timestamp_A],  
             'timestamp_B' : [timestamp_B],
             'action_code': [action_code],
            }    
    df = pd.DataFrame(data)
    df.to_csv(vosaic_sketch_tags,mode ='a' , index=False, header=False)

intervals

[[0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0]]

In [44]:
for i in range(len(arr)):
    intervals[i][0] = string_to_sec(arr[i][0])
    intervals[i][1] = string_to_sec(arr[i][1])

intervals

[[380, 385],
 [392, 396],
 [407, 413],
 [609, 639],
 [653, 657],
 [2479, 2742],
 [2482, 4075],
 [2798, 2865],
 [2888, 3203],
 [3241, 3356],
 [3417, 3705],
 [3739, 3802],
 [3936, 4218],
 [4077, 4104],
 [4110, 4114],
 [4117, 4143],
 [4163, 4182],
 [4186, 4296],
 [4256, 4361],
 [4298, 4364],
 [4370, 4372],
 [4404, 4410],
 [4421, 4439],
 [4472, 4478],
 [4514, 4753],
 [4773, 4826],
 [4879, 5054],
 [5075, 5286],
 [5294, 5343],
 [5698, 5710],
 [5713, 5724]]

In [45]:
# Python program to merge overlapping Intervals in
# O(n Log n) time and O(1) extra space


def mergeIntervals(arr):

	# Sorting based on the increasing order
	# of the start intervals
	arr.sort(key=lambda x: x[0])

	# Stores index of last element
	# in output array (modified arr[])
	index = 0

	# Traverse all input Intervals starting from
	# second interval
	for i in range(1, len(arr)):

		# If this is not first Interval and overlaps
		# with the previous one, Merge previous and
		# current Intervals
		if (arr[index][1] >= arr[i][0]):
			arr[index][1] = max(arr[index][1], arr[i][1])
		else:
			index = index + 1
			arr[index] = arr[i]

	return arr


merged = mergeIntervals(intervals)

merged

[[380, 385],
 [392, 396],
 [407, 413],
 [609, 639],
 [653, 657],
 [2479, 4364],
 [4370, 4372],
 [4404, 4410],
 [4421, 4439],
 [4472, 4478],
 [4514, 4753],
 [4773, 4826],
 [4879, 5054],
 [5075, 5286],
 [5294, 5343],
 [5698, 5710],
 [5713, 5724],
 [4186, 4296],
 [4256, 4361],
 [4298, 4364],
 [4370, 4372],
 [4404, 4410],
 [4421, 4439],
 [4472, 4478],
 [4514, 4753],
 [4773, 4826],
 [4879, 5054],
 [5075, 5286],
 [5294, 5343],
 [5698, 5710],
 [5713, 5724]]

In [46]:
res = np.unique(np.array([np.sort(sub) for sub in merged]), axis=0)

In [47]:
len(res)

20

In [48]:
res

array([[ 380,  385],
       [ 392,  396],
       [ 407,  413],
       [ 609,  639],
       [ 653,  657],
       [2479, 4364],
       [4186, 4296],
       [4256, 4361],
       [4298, 4364],
       [4370, 4372],
       [4404, 4410],
       [4421, 4439],
       [4472, 4478],
       [4514, 4753],
       [4773, 4826],
       [4879, 5054],
       [5075, 5286],
       [5294, 5343],
       [5698, 5710],
       [5713, 5724]])

In [49]:
video_limit  = string_to_sec(vosaic_video_duration)
video_limit

5724

In [50]:
time_array = [] 
for i in range(video_limit):
    time_array.append(0)

for i in range(len(res)):
    for j in range (res[i][0],res[i][1]):
        time_array[j] = 1

In [51]:
for i in range(buffer,len(time_array)):
    timestamp_A = mil_convert((i*1000))
    timestamp_B = mil_convert((i+1)*1000)
    action_code = time_array[i]
    data = { 
             'timestamp_A' : [timestamp_A],  
             'timestamp_B' : [timestamp_B],
             'action_code': [action_code],
            }    
    df = pd.DataFrame(data)
    df.to_csv(vosaic_sketch_tags,mode ='a' , index=False, header=False)